name: Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to destroy the infrastructure?'
        required: true
        type: boolean

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Destroy Infrastructure
        run: |
          if [ ${{ github.event.inputs.confirm }} = true ]; then
              echo "Destroying infrastructure..."
          else
              echo "Infrastructure destruction cancelled."
              exit 1
          fi
        shell: bash

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Replace Tokens with Environment Variables
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.tfvars.tmpl"]'
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          FE_BUCKET_NAME: ${{vars.FE_BUCKET_NAME}}
          CLOUDFRONT_PRICE_CLASS: ${{vars.CLOUDFRONT_PRICE_CLASS}}
          CLOUDFRONT_CACHE_POLICY_ID: ${{vars.CLOUDFRONT_CACHE_POLICY_ID}}
          TF_ORGANISATION: ${{secrets.TF_ORGANISATION}}
          TF_WORKSPACE: ${{secrets.TF_WORKSPACE}}

      - name: Rename .tfvars.tmpl to .tfvars
        run: |
          find . -name "*.tfvars.tmpl" -exec sh -c 'mv "$1" "${1%.tmpl}"' _ {} \;

      - name: Terraform Init
        shell: bash
        run: terraform -chdir=terraform init

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
